# Generated by Django 4.1.3 on 2022-11-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': '응답'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': '다이어리'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '질문'},
        ),
    ]
