# Generated by Django 4.1.3 on 2022-11-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_diary_audio_dirs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='qna.answer', verbose_name='응답'),
        ),
    ]
