# Generated by Django 4.1.3 on 2022-11-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_alter_diary_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='qna.question', verbose_name='질문'),
        ),
    ]
